[package]
name = "libpopt"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "http://ftp.rpm.org/popt/releases/popt-1.x"

[[package.metadata.build-package.external-files]]
url = "http://ftp.rpm.org/popt/releases/popt-1.x/popt-1.19.tar.gz"
sha512 = "5d1b6a15337e4cd5991817c1957f97fc4ed98659870017c08f26f754e34add31d639d55ee77ca31f29bb631c0b53368c1893bd96cf76422d257f7997a11f6466"
force-upstream = true

[build-dependencies]
glibc = { path = "../glibc" }

