[package]
name = "libtss2"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
package-name = "libtss2"
releases-url = "https://github.com/tpm2-software/tpm2-tss/releases/download"

[[package.metadata.build-package.external-files]]
url = "https://github.com/tpm2-software/tpm2-tss/releases/download/4.1.3/tpm2-tss-4.1.3.tar.gz"
sha512 = "c9a5e1e90f6545a466d43790ab2d67c52c4b788a0b21f8212575e27e04e0ac663105863fe00824e08a4e56a4f8c6b00c48c1a1c132531b8569cd5042c3bb9e69"
force-upstream = true

[build-dependencies]
glibc = { path = "../glibc" }
aws-lc-fips = { path = "../aws-lc-fips" }
