[package]
name = "aws-lc-fips"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://github.com/aws/aws-lc/archive"

[[package.metadata.build-package.external-files]]
url = "https://github.com/aws/aws-lc/archive/AWS-LC-FIPS-3.0.0/aws-lc-AWS-LC-FIPS-3.0.0.tar.gz"
sha512 = "4457edaacd1f93d8f9f71c960272b44004fe9f6dd65ed6a0c4eabd7d870487c9e9ac38efa8375dfeae3729752e9a477719d05f534c33965f546ca4a883e123c8"
force-upstream = true

[build-dependencies]
glibc = { path = "../glibc" }
