[package]
name = "libaio"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "http://releases.pagure.org/libaio"

[[package.metadata.build-package.external-files]]
url = "http://releases.pagure.org/libaio/libaio-0.3.111.tar.gz"
sha512 = "440f2b62f99ca2e72ffc8c2c04b4779a1a7cf24a8ba2a30b34d18b4ee77630a2078610fe8c435559f81a5c3bfa93049bd53d77464a0da8267833fbde3f40ceeb" 
force-upstream = true

[build-dependencies]
glibc = { path = "../glibc" }
