[package]
name = "device-mapper"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://sourceware.org/lvm2"

[[package.metadata.build-package.external-files]]
url = "https://sourceware.org/pub/lvm2/releases/LVM2.2.03.29.tgz"
sha512 = "2d5dfde81007fcf34752b19e9edc9ab8189449f572429e973317b968c5a99b886dc26e81dc29c3cf5b7678da0f8a7e8c060431a33b950f6ff6279dfbddd9c7b2" 
force-upstream = true

[build-dependencies]
glibc = { path = "../glibc" }
libselinux = { path = "../libselinux" }
systemd = { path = "../systemd" }
libaio = { path = "../libaio" }
