[package]
name = "libargon2"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
package-name = "libargon2"
releases-url = "https://github.com/P-H-C/phc-winner-argon2/releases/download"

[[package.metadata.build-package.external-files]]
url = "https://github.com/P-H-C/phc-winner-argon2/archive/refs/tags/20190702.tar.gz"
sha512 = "0a4cb89e8e63399f7df069e2862ccd05308b7652bf4ab74372842f66bcc60776399e0eaf979a7b7e31436b5e6913fe5b0a6949549d8c82ebd06e0629b106e85f"
force-upstream = true 
